// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
//
//  Generated on Fri Apr 18 2025
// -------------------------------------------------------
export type FontFamilyAndWeight =
  | "Poppins-bold"
  | "Poppins-semiBold"
  | "Poppins-medium"
  | "Poppins-regular"
  | "Poppins-light"
  | "Inter-bold"
  | "Inter-semiBold"
  | "Inter-medium"
  | "Inter-regular"
  | "Inter-light"
  | "Mulish-bold"
  | "Mulish-semiBold"
  | "Mulish-medium"
  | "Mulish-regular"
  | "Mulish-light"
  | "Consolas-bold"
  | "Consolas-semiBold"
  | "Consolas-medium"
  | "Consolas-regular"
  | "Consolas-light";
export type MakeFontWeight = (fontWeightName: FontFamilyAndWeight) => string;

/**
 * ## `makeFontWeight`
 * A utility that returns the CSS variable assigned to keys of the `font.family`
 */
export const makeFontWeight: MakeFontWeight = (fontFamilyAndWeight) => {
  return `var(studio-${fontFamilyAndWeight})`;
};
