// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
// -------------------------------------------------------
export type Breakpoints = "phone" | "tablet" | "desktop";
export type MakeResponsive = (params: {
  from?: Breakpoints;
  to?: Breakpoints;
}) => string;

/**
* ## `makeResponsive`
* A utility that enables you to easily create a `@media`
string that can be interpolated in CSS-in-JS syntax.
*/
export const makeResponsive: MakeResponsive = (params) => {
  const from = params?.from
    ? `var(--studio-breakpoint-${params.from})`
    : undefined;
  const to = params?.to
    ? `calc(var(--studio-breakpoint-${params.to}) - 1px)`
    : undefined;
  if (from && to) {
    return `@media (min-width: ${from}) and @media (max-width:${to})`;
  }
  if (from && !to) {
    return `@media (min-width: ${from})`;
  }
  if (to && !from) {
    return `@media (max-width: ${to})`;
  }
  throw new Error("You must provide a to or from parameter.");
};
