// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
//
//  Generated on Thu Apr 17 2025
// -------------------------------------------------------
export type FontFamilyAndWeight =
  | "heading-regular"
  | "heading-semiBold"
  | "heading-bold"
  | "body-regular"
  | "body-medium"
  | "body-semiBold"
  | "formal-regular"
  | "formal-medium"
  | "formal-semiBold"
  | "formal-bold"
  | "formal-black";
export type MakeFontWeight = (fontWeightName: FontFamilyAndWeight) => string;

/**
 * ## `makeFontWeight`
 * A utility that returns the CSS variable assigned to keys of the `font.family`
 */
export const makeFontWeight: MakeFontWeight = (fontFamilyAndWeight) => {
  return `var(studio-${fontFamilyAndWeight})`;
};
