// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
//
//  Generated on Fri Apr 18 2025
// -------------------------------------------------------
export type FontFamily = "Poppins" | "Inter" | "Mulish" | "Consolas";
export type MakeFontFamily = (fontFamilyName: FontFamily) => string;

/**
 * ## `makeFontFamily`
 * A utility that returns the CSS variable assigned to the font-family`
 */
export const makeFontFamily: MakeFontFamily = (value) => {
  return `var(--studio-font-family-${value})`;
};
